Fix SQL error detection problems.

diff --git a/git-config/hooks/post-merge b/git-config/hooks/post-merge
--- a/git-config/hooks/post-merge
+++ b/git-config/hooks/post-merge
@@ -12,9 +12,14 @@ if ( echo "$CHANGED_FILES" | grep --quiet $MYSQL_SCHEMA_UPDATES_PATH_LOCAL ); th
     if [[ -x $MYSQL_DATABASE_PATCHER ]]; then
 	echo "Executing MYSQL schema updates tool"
         $MYSQL_DATABASE_PATCHER $MYSQL_SCHEMA_UPDATES_PATH
+        if [[ $? != 0 ]]; then
+            echo "$MYSQL_DATABASE_PATCHER $MYSQL_SCHEMA_UPDATES_PATH failed!"
+            exit 1
+        fi
         /usr/local/bin/mysql_list_tables > /tmp/new_ub_tools.schema
         /usr/local/bin/mysql_diff_schemas /tmp/old_ub_tools.schema /tmp/new_ub_tools.schema
         compare_against_installer_schema=1
+        echo "MYSQL schema update completed"
     else
         echo "You need to install $MYSQL_DATABASE_PATCHER and execute it!."
         exit 1
@@ -37,5 +42,7 @@ if [[ $compare_against_installer_schema && -r /tmp/new_ub_tools.schema ]]; then
     if [ -s /tmp/schema_diffs ]; then
         MYSQL_DB=$(inifile_lookup /usr/local/var/lib/tuelib/ub_tools.conf Database sql_database)
         echo "**** The patched $MYSQL_DB database schema differs from the one that the installer uses.  You *must* fix this"'! ****'
+    else
+        echo "Verification successful! (The current DB schema was successfully compared to the installer's DB schema.)"
     fi
 fi
